<?php

/*
 * ************** CAUTION **************
 *
 * DO NOT EDIT THIS FILE as it will be overridden by Composer as part of
 * the installation/update process. The original file resides in the
 * SensioDistributionBundle.
 *
 * ************** CAUTION **************
 */

if (PHP_SAPI !== 'cli' && !isset($_SERVER['HTTP_HOST'])) {
    exit('This script cannot be run from the CLI. Run it from a browser.');
}

$allowedRemoteAddresses = array(
    '127.0.0.1',
    '::1',
);

if (!in_array(getRemoteAddress(), $allowedRemoteAddresses)) {
    header('HTTP/1.0 403 Forbidden');
    exit('This script is only accessible from localhost.');
}

require_once dirname(__FILE__).'/../var/SymfonyRequirements.php';

// Check if the SymfonyRequirements class exists before instantiating it
if (class_exists('SymfonyRequirements')) {
    $symfonyRequirements = new SymfonyRequirements();

    $majorProblems = $symfonyRequirements->getFailedRequirements();
    $minorProblems = $symfonyRequirements->getFailedRecommendations();
    $hasMajorProblems = (bool) count($majorProblems);
    $hasMinorProblems = (bool) count($minorProblems);
} else {
    // Handle the case where SymfonyRequirements class is not available
    exit('SymfonyRequirements class is not available. Please check your installation.');
}

function getRemoteAddress() {
    return $_SERVER['REMOTE_ADDR'];
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="robots" content="noindex,nofollow" />
    <title>Symfony Configuration Checker</title>
    <!-- ... Vos autres balises meta et styles ... -->
</head>
<body>
<div id="content">
    <!-- ... Le contenu de votre page ... -->
</div>
</body>
</html>
